name: yacabadmin
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
#  fdottedline: ^1.0.1
  url_launcher: ^6.1.4
#  flutter_inappwebview: ^5.3.2
#  flutter_webview_plugin: ^0.3.11
  image_picker: ^0.8.5+3
  flutter_polyline_points: ^1.0.0
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.4
#  workmanager: ^0.4.1
  path_provider: ^2.0.11

  maps_launcher: ^2.0.1
  flutter_share: ^2.0.0
  open_file: ^3.2.1
  pdf: ^3.8.1
  firebase_messaging: ^11.4.2


#  flutter_instamojo: ^1.0.0
  #stripe_payment: ^1.1.1
  razorpay_flutter: ^1.3.0
#    git:
#      url: git://github.com/razorpay/razorpay-flutter.git
#      ref: master

#  flutter_local_notifications:
  mailer: ^5.1.1
  store_redirect: ^2.0.1
  firebase: ^9.0.3
#  youtube_player_iframe: ^2.2.2
#  double_back_to_close_app: ^2.0.1
#  flutter_cart: ^0.0.5+1
#  flutter_icons: ^1.1.0
  material_design_icons_flutter: ^5.0.6595
  connectivity_plus: ^2.3.5
#  carousel_pro: ^1.0.0
#  email_validator: ^1.0.4
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.5

#  toast: ^0.1.5
#  html: ^0.14.0+4
#  expandable: ^4.1.4
#  dio: ^3.0.10
#  animated_dialog_box:
  flutter_animated_dialog: ^2.0.1
  carousel_slider: ^4.1.1
  firebase_auth: ^3.3.20
  firebase_database: ^9.0.16
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
#  shimmer: ^1.1.2
  http: ^0.13.1
#  flutter_session:
#  intro_slider: ^3.0.2
  flutter_spinkit: ^5.1.0
  hexcolor: ^2.0.7
  shared_preferences: ^2.0.15
  pin_entry_text_field: ^0.1.4
  pin_code_text_field: ^1.8.0
  permission_handler: ^10.0.0
  google_maps_flutter: ^2.1.8
#  location: ^3.2.4
#    git:
#      url: git://github.com/dreambitio/flutterlocation.git
#      ref: release/3.2.4
#      path: location/
#  charts_flutter: ^0.6.0
  geolocator: ^9.0.0
#  geocoder: ^0.2.1
  flutter_share_me: ^1.3.0
  intl: ^0.17.0
#  json_serializable: ^3.3.0
#  video_player: ^2.1.1
#  smooth_star_rating: ^1.1.1
  multi_image_picker2: ^5.0.2

#DEPENDENCIES FOR CONTACT ACCESS
#  validators: ^2.0.0+1
  path: ^1.8.1
#  meta: ^1.1.8
#  vcard:
#  contacts_service: ^0.4.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/Logo.jpeg
    - images/Logo.png
    - images/Logo2.png
    - images/Logo3.png
    - images/LocationPermission.png
    - images/OTPVerified.gif


  fonts:
    - family: Fredoka One
      fonts:
        - asset: fonts/Bodoni.ttf
